### PR TITLE
`include` and basic namespaces

### LINKED ISSUE #12: Implement "#include"
This preprocessor directive will allow for programs with multiple files/modules.

Example:

**test.tin**

```
fn i32 test
{
  print "test\n";
}
```
**main.tin**

```
#include "test.tin"

fn i32 main
{
  test();
}
```

### PR DESCRIPTION
**Pull request by aaf6aa**
Allowed the use of more than one file using the `include` keyword and namespaces, and moving the parsing code from main into `module.c`. Also added a portable path handling utility.

closes #12

### CODE REVIEW

**Review by kazaxc — COMMENTED** [review]
Code matches proposed changes for adding includes and namespaces a final check by @xezno is needed to make sure that the backend systems line up correctly and to see if any additional changes are needed.

**Comment by xezno** [comment]
Don't know if I'm missing anything but it seems like there's no way to differentiate between symbols that exist in different namespaces?
image

**Comment by aaf6aa** [comment]
Sorry, the AST JSON output isn't specific enough so symbols with identical names will also appear the same to the human reader, but they are different and reference different symbols in-memory. I added an ID (their address originally) to each symbol in the output to distinguish them.
image

**Comment by xezno** [comment]
Yeah, everything should work fine then I believe

**Pull request merged**
